# Generated by Django 5.2.6 on 2025-10-02 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(default='post/default.jpg', null=True, upload_to='post'),
        ),
    ]
